version: '3.8'

services:
  axiestudio:
    image: axiestudio/swedish:latest
    ports:
      - "7860:7860"
    environment:
      # 🗄️ Supabase PostgreSQL Database
      - AXIESTUDIO_DATABASE_URL=postgresql://postgres:STEfanjohn!12@db.ompjkiiabyuegytncbwq.supabase.co:5432/postgres
      
      # 🔐 Authentication Settings
      - AXIESTUDIO_AUTO_LOGIN=false
      
      # 🌐 Server Configuration
      - AXIESTUDIO_HOST=0.0.0.0
      - AXIESTUDIO_PORT=7860
      
      # 🔒 Security Settings (Change in production!)
      - AXIESTUDIO_SECRET_KEY=production-secret-key-change-this
      - AXIESTUDIO_JWT_SECRET=production-jwt-secret-change-this
      
      # 📊 Logging & Performance
      - AXIESTUDIO_LOG_LEVEL=INFO
      - AXIESTUDIO_DEBUG=false
      - AXIESTUDIO_WORKERS=1
      
    volumes:
      # Only need local storage for uploads/cache (database is in Supabase)
      - axiestudio_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/health_check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s  # Longer start period for database connection
    depends_on: []  # No local database dependency

volumes:
  axiestudio_data:
    driver: local
