name: 'Tauri Build'

on:
  push:
    branches: [ tauri-en ]
  pull_request:
    branches: [ tauri-en ]

jobs:
  tauri:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target universal-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # Disable npm cache to avoid optional dependency issues
          # cache: 'npm'
          # cache-dependency-path: src/frontend/package-lock.json

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            librsvg2-dev \
            patchelf \
            libgtk-3-dev \
            libxdo-dev \
            libssl-dev
          # Install only one appindicator package to avoid conflicts
          sudo apt-get install -y libayatana-appindicator3-dev || sudo apt-get install -y libappindicator3-dev

      - name: install frontend dependencies
        run: |
          # Fix npm optional dependencies issue with Rollup
          rm -rf node_modules package-lock.json || true
          npm install
        working-directory: src/frontend
        shell: bash

      - name: build frontend
        run: npm run build
        working-directory: src/frontend

      - name: Setup Tauri icons from existing favicon/logo
        run: |
          mkdir -p src-tauri/icons
          # Copy existing favicon and logo files to Tauri icons directory
          cp src/frontend/public/favicon.ico src-tauri/icons/icon.ico
          cp src/frontend/public/favicon.svg src-tauri/icons/icon.svg
          cp src/frontend/public/logo512.png src-tauri/icons/icon.png
          cp src/frontend/public/logo192.png src-tauri/icons/128x128.png
          cp src/frontend/public/favicon_io/favicon-32x32.png src-tauri/icons/32x32.png
          cp src/frontend/public/favicon_io/apple-touch-icon.png src-tauri/icons/icon.icns
          cp src/frontend/public/favicon_io/android-chrome-512x512.png src-tauri/icons/512x512.png
          # List created icons for debugging
          ls -la src-tauri/icons/
        shell: bash

      - name: Debug - Check build output
        run: |
          echo "Checking if build directory exists..."
          ls -la src/frontend/build || echo "Build directory not found"
        shell: bash

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Don't create releases automatically to avoid permission issues
          # tagName: app-v__VERSION__
          # releaseName: 'App v__VERSION__'
          # releaseBody: 'See the assets to download this version and install.'
          # releaseDraft: true
          # prerelease: false
          args: ${{ matrix.args }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-artifacts-${{ matrix.platform }}
          path: |
            src-tauri/target/release/bundle/
            src-tauri/target/universal-apple-darwin/release/bundle/
          retention-days: 30
